### ISSUE TITLE
An environmental integration issue

### ISSUE THREAD

**Issue by dreamflyings** [SingularityKChen/dl_accelerator#19]
Chipyard is a pipular learning platform. Can you integtate your code, especially test code, into the environment of chipyard?

**Comment by SingularityKChen** [comment]
Hi, `Rocket-Playground` is the mill version of Chipyard, they're similar. And you can follow the steps in `README`. If you meet any problem, you can ask me with the screenshots.

**Comment by dreamflyings** [comment]
@SingularityKChen Ok, thanks~
